// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsljHyAiZgSnJIoUPRhmope_PZHkE6x-I',
    appId: '1:424205941920:web:52f3682c2c7c808ed65dc5',
    messagingSenderId: '424205941920',
    projectId: 'cafeteriaapp-80588',
    authDomain: 'cafeteriaapp-80588.firebaseapp.com',
    storageBucket: 'cafeteriaapp-80588.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVptZR-aJXhI2ceL13PDe2rce_MSUPDcs',
    appId: '1:424205941920:android:4e631d8b0b4a8245d65dc5',
    messagingSenderId: '424205941920',
    projectId: 'cafeteriaapp-80588',
    storageBucket: 'cafeteriaapp-80588.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtBv418IV3OTJBYI7I1ilADCvfEpPFNIc',
    appId: '1:424205941920:ios:1cabb92cff3f237cd65dc5',
    messagingSenderId: '424205941920',
    projectId: 'cafeteriaapp-80588',
    storageBucket: 'cafeteriaapp-80588.firebasestorage.app',
    iosBundleId: 'com.example.cafeteriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtBv418IV3OTJBYI7I1ilADCvfEpPFNIc',
    appId: '1:424205941920:ios:1cabb92cff3f237cd65dc5',
    messagingSenderId: '424205941920',
    projectId: 'cafeteriaapp-80588',
    storageBucket: 'cafeteriaapp-80588.firebasestorage.app',
    iosBundleId: 'com.example.cafeteriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsljHyAiZgSnJIoUPRhmope_PZHkE6x-I',
    appId: '1:424205941920:web:238eb1560e6a2f6ad65dc5',
    messagingSenderId: '424205941920',
    projectId: 'cafeteriaapp-80588',
    authDomain: 'cafeteriaapp-80588.firebaseapp.com',
    storageBucket: 'cafeteriaapp-80588.firebasestorage.app',
  );
}
