import 'package:cafeteria_app/providers/auth_provider.dart' as MyAppAuthProvider; // Alias
import 'package:cafeteria_app/providers/cart_provider.dart';
import 'package:cafeteria_app/screens/home_screen.dart';
import 'package:cafeteria_app/screens/splash_screen.dart';
import 'package:cafeteria_app/utils/app_colors.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'firebase_options.dart'; // Auto-generated by FlutterFire CLI or manually added

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => MyAppAuthProvider.AuthProvider()),
        ChangeNotifierProvider(create: (_) => CartProvider()),
      ],
      child: MaterialApp(
        title: 'Cafeteria App',
        theme: ThemeData(
          primarySwatch: AppColors.orangeMaterial, // Custom material color from orange
          scaffoldBackgroundColor: Colors.white, // Default scaffold bgtextTheme: GoogleFonts.latoTextTheme(Theme.of(context).textTheme), // Example stylish font
          appBarTheme: const AppBarTheme(
            backgroundColor: Colors.orangeAccent,
            elevation: 0,
            iconTheme: IconThemeData(color: Colors.white),
            titleTextStyle: TextStyle(
              color: Colors.white,
              fontSize: 20,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
        home: Consumer<MyAppAuthProvider.AuthProvider>(
          builder: (context, auth, _) {
            if (auth.isAuthenticated) {
              return HomeScreen(); // If logged in, go to Home
            }
            return SplashScreen(); // Else, start with Splash
          },
        ),
        // Define routes for navigation
        routes: {
          '/home': (context) => HomeScreen(),
          // Add other routes as needed
        },
      ),
    );
  }
}